# Generated by Django 3.0.5 on 2020-05-01 19:34

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('monument', 'monument'), ('museum', 'museum')], max_length=30)),
                ('main_picture', models.ImageField(null=True, upload_to='media/main_pictures/')),
                ('brief_description', models.TextField()),
                ('full_description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_text', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='media/audio/')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='GeneralMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('map_x', models.CharField(max_length=200)),
                ('map_y', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General Map',
                'verbose_name_plural': 'General Map',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('highlight_x', models.CharField(max_length=200)),
                ('highlight_y', models.CharField(max_length=200)),
                ('pin_x', models.CharField(max_length=200)),
                ('pin_y', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('route_x', models.CharField(max_length=200)),
                ('route_y', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Museums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('website', models.CharField(max_length=200, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tickets', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('monument', 'monument'), ('museum', 'museum')], max_length=30)),
                ('main_picture', models.ImageField(null=True, upload_to='media/main_pictures/')),
                ('brief_description', models.TextField()),
                ('full_description', models.TextField(null=True)),
                ('audio_text', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='media/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Language')),
                ('layers', models.ManyToManyField(blank=True, related_name='museums', to='dashboard.Layers')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Map')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Price')),
                ('section', models.ManyToManyField(blank=True, related_name='museums', to='dashboard.Sections')),
            ],
            options={
                'verbose_name': 'Museum',
                'verbose_name_plural': 'Museums',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallery/')),
                ('brief_description', models.TextField()),
                ('articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Articles')),
                ('museums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Museums')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.Language'),
        ),
        migrations.AddField(
            model_name='articles',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='articles', to='dashboard.Layers'),
        ),
        migrations.AddField(
            model_name='articles',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.Map'),
        ),
        migrations.AddField(
            model_name='articles',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='articles', to='dashboard.Sections'),
        ),
    ]
