# Generated by Django 3.0.5 on 2020-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalmap',
            old_name='map_x',
            new_name='map_x_y',
        ),
        migrations.RemoveField(
            model_name='generalmap',
            name='map_y',
        ),
        migrations.AddField(
            model_name='generalmap',
            name='zoom',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
