# Generated by Django 3.0.5 on 2020-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200502_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmap',
            name='sequence',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='brief_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('monument', 'monument'), ('museum', 'museum'), ('small_objects', 'small_objects')], max_length=30),
        ),
        migrations.AlterField(
            model_name='museums',
            name='brief_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='museums',
            name='type',
            field=models.CharField(choices=[('monument', 'monument'), ('museum', 'museum'), ('small_objects', 'small_objects')], max_length=30),
        ),
    ]
