# Generated by Django 3.0.4 on 2020-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200323_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='title',
            field=models.CharField(default=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='layers',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='museums',
            name='website',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
