# Generated by Django 3.0.4 on 2020-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200323_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='full_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='full_description_en',
            field=models.TextField(null=True),
        ),
    ]
