# Generated by Django 3.0.4 on 2020-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200323_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='full_description_de',
        ),
        migrations.AlterField(
            model_name='route',
            name='route_x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_y',
            field=models.CharField(max_length=200),
        ),
    ]
