# Generated by Django 3.0.5 on 2020-07-06 10:31

import dashboard.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200503_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Articles'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='museums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Museums'),
        ),
    ]
