# Generated by Django 3.0.5 on 2020-07-15 22:46

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200706_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sequence',
            field=models.FloatField(default=0),
            preserve_default=False,
        )
    ]
