# Generated by Django 3.0.4 on 2020-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200328_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='highlight_x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='highlight_y',
            field=models.CharField(max_length=200),
        ),
    ]
