# Generated by Django 3.0.4 on 2020-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200404_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('map_x', models.CharField(max_length=200)),
                ('map_y', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General Map',
                'verbose_name_plural': 'General Map',
            },
        ),
    ]
