# Generated by Django 3.0.5 on 2021-04-27 12:56

import dashboard.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200912_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='audio_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_audio_language', to='dashboard.Language', verbose_name='Article Audio Language'),
        ),
        migrations.AddField(
            model_name='articles',
            name='brief_description_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_brief_description_language', to='dashboard.Language', verbose_name='Article Brief Description Language'),
        ),
        migrations.AddField(
            model_name='articles',
            name='full_description_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_full_description_language', to='dashboard.Language', verbose_name='Article Full Description Language'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_title_language', to='dashboard.Language', verbose_name='Article Title Language'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='brief_description_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries_brief_description_language', to='dashboard.Language', verbose_name='Galleries Brief Description Language'),
        ),
        migrations.AddField(
            model_name='layers',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers_title_language', to='dashboard.Language', verbose_name='Layers Title Language'),
        ),
        migrations.AddField(
            model_name='map',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_title_language', to='dashboard.Language', verbose_name='Map Title Language'),
        ),
        migrations.AddField(
            model_name='museums',
            name='brief_description_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums_brief_description_language', to='dashboard.Language', verbose_name='Museums Brief Description Language'),
        ),
        migrations.AddField(
            model_name='museums',
            name='full_description_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums_full_description_language', to='dashboard.Language', verbose_name='Museums Full Description Language'),
        ),
        migrations.AddField(
            model_name='museums',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums_title_language', to='dashboard.Language', verbose_name='Museums Title Language'),
        ),
        migrations.AddField(
            model_name='route',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_title_language', to='dashboard.Language', verbose_name='Route Title Language'),
        ),
        migrations.AddField(
            model_name='sections',
            name='title_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_title_language', to='dashboard.Language', verbose_name='Sections Title Language'),
        ),
    ]
