# Generated by Django 3.0.5 on 2021-04-27 18:44

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210427_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='three_d_panoramas',
            field=models.FileField(default=False, upload_to='media/gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='three_d_tour',
            field=models.FileField(default=False, upload_to='media/gallery/'),
            preserve_default=False,
        ),
    ]
