# Generated by Django 3.0.4 on 2020-04-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200406_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='brief_description',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museums',
            name='brief_description',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
