# Generated by Django 3.0.4 on 2020-04-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200410_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.Language'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.Map'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Articles'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='museums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.Museums'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Language'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Map'),
        ),
        migrations.AlterField(
            model_name='museums',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to='dashboard.Price'),
        ),
    ]
