# Generated by Django 3.0.5 on 2020-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200410_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmap',
            name='map_x',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='generalmap',
            name='map_y',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='pin_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='pin_y',
            field=models.FloatField(default=0),
        ),
    ]
